-- Optional: clear table before inserting
TRUNCATE TABLE bingo_cards_phrases RESTART IDENTITY;
TRUNCATE TABLE bingo_phrases RESTART IDENTITY CASCADE;

-- Insert phrases
INSERT INTO bingo_phrases (phrase, phrase_type) VALUES
('Footy talk', 'NORMAL'),
('Somebody accused of drinking too much', 'NORMAL'),
('Viv mentions Parkrun', 'NORMAL'),
('Nat mentions Mr Warsons', 'NORMAL'),
('Food complaint', 'NORMAL'),
('Service complaint', 'NORMAL'),
('Building temperature complaint', 'NORMAL'),
('3 different people named Sue are mentioned', 'NORMAL'),
('Mild Homophobia', 'NORMAL'),
('Severe Homophobia', 'NORMAL'),
('ChatGPT', 'NORMAL'),
('"Who`s going to have a baby first?"', 'NORMAL'),
('"Who`s going to get married first?"', 'NORMAL'),
('"Ravaged by Wolves"', 'DECLARE'),
('"Mugged by Monkeys"', 'DECLARE'),
('"Parting is such sweet sorrow"', 'DECLARE'),
('"Bombaclaat"', 'DECLARE'),
('"I am going on holiday to Minsk in 2026"', 'DECLARE'),
('"In 2026 I`m going to stop smoking"', 'DECLARE'),
('"Gag me with a spoon!"', 'DECLARE'),
('"This is vegan right?"', 'DECLARE'),
('"Are you accusing me of being an alcoholic?"', 'DECLARE'),
('Woke Nonsense', 'PATRIOT'),
('Nigel Farage', 'PATRIOT'),
('Bloody Labour', 'PATRIOT'),
('Just Stop Oil!?', 'PATRIOT'),
('Reform UK', 'PATRIOT'),
('Swap two people`s drinks', 'CHALLENGE'),
('Randomly sing Happy Birthday', 'CHALLENGE'),
('Convince somebody there is a regular beep', 'CHALLENGE'),
('A highly noteworthy fake phone call', 'CHALLENGE'),
('Get 5 people clapping at the same time', 'CHALLENGE'),
('Get a stranger to wish Viv Happy Birthday', 'CHALLENGE'),
('Convince somebody you`re changing career', 'CHALLENGE'),
('Get somebody to remove a shoe', 'CHALLENGE');